trigger:
  branches:
    include:
      - master
      - feature/*
      - Feature/*
  paths:
    exclude:
      - README.md
      - cake/*

pr:
  autoCancel: true
  branches:
    include:
    - master

pool:
    vmImage: 'ubuntu-latest'

variables:
    buildConfiguration: 'Release'
    NETCoreVersion: '7.0.x'
    solutionFile: '$(Build.SourcesDirectory)/*.sln'
    unitTestPath: '$(Build.SourcesDirectory)/source/Services/product-catalog/DDD.ProductCatalog.Tests'
    unitTestProjects: '$(unitTestPath)/*Tests/*.csproj'
    codeCoverageReportPath : '$(Build.SourcesDirectory)/CodeCoverage'

stages:
- stage: RunBuild
  displayName: 'Run Build'
  jobs:
  - job: BuildJob
    steps:
    #############
    # Install .net core
    #############
    - task: UseDotNet@2
      displayName: "Install .NET Core $(NETCoreVersion)"
      inputs: 
        version: '$(NETCoreVersion)'
    #############
    # dotnet restore solution
    #############
    - task: DotNetCoreCLI@2
      displayName: "dotnet restore"
      inputs:
          command: 'restore'
          projects: '$(solutionFile)'
    #############
    # dotnet build solution
    #############
    - task: DotNetCoreCLI@2
      displayName: "dotnet build"
      inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration)'
          projects: '$(solutionFile)'

- stage: RunTests
  displayName: 'Run Tests'
  jobs:
  - job: RunTestsJob
    displayName: 'Run Tests Projects'
    steps:
    - task: UseDotNet@2
      displayName: "Install .NET Core $(NETCoreVersion)"
      inputs: 
        version: '$(NETCoreVersion)'
    #############
    # dotnet test
    #############
    - task: DotNetCoreCLI@2
      displayName: "dotnet test"
      inputs:
        command: test
        projects: '$(unitTestProjects)'
        arguments: '--configuration $(BuildConfiguration) /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura'
        nobuild: true

    - script: |
        dotnet tool install -g dotnet-reportgenerator-globaltool --version 4.3.8
        $HOME/.dotnet/tools/reportgenerator -reports:$(unitTestPath)/**/coverage.cobertura.xml -targetdir:$(codeCoverageReportPath) -reporttypes:Cobertura
      displayName: 'Create Code coverage report'

    - task: PublishCodeCoverageResults@1
      continueOnError: true
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(codeCoverageReportPath)/Cobertura.xml'
        reportDirectory: '$(codeCoverageReportPath)'
        failIfCoverageEmpty: true

    

- stage: CleanUp
  displayName: "Cleanup After Build"
  jobs:
    - job: "CleanUpJob"
      steps:
      - task: DeleteFiles@1
        continueOnError: true
        inputs:
          SourceFolder: '$(Agent.BuildDirectory)'
          Contents: '**/*'
          RemoveSourceFolder: true
